# Generated by Django 3.2.6 on 2021-10-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Styles',
            new_name='Style',
        ),
    ]
