# Generated by Django 3.2.6 on 2021-10-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nationalitiesandperiods', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(max_length=300, null=True)),
                ('summary', models.TextField(null=True)),
                ('year_of_writting', models.IntegerField(null=True)),
                ('number_of_pages', models.IntegerField(blank=True)),
                ('author', models.ForeignKey(blank=True, max_length=254, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author')),
                ('genre', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book_genre')),
                ('period', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nationalitiesandperiods.period')),
            ],
        ),
    ]
