# Generated by Django 3.2.6 on 2021-10-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('base', '0002_auto_20211026_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(max_length=254, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author'),
        ),
    ]
