# Generated by Django 3.2.6 on 2021-10-31 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('base', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(max_length=254, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='authors.author'),
        ),
    ]
