# Generated by Django 3.2.6 on 2021-10-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nationalitiesandperiods', '0001_initial'),
        ('authors', '0001_initial'),
        ('base', '0003_rename_styles_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, max_length=254, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='period',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nationalitiesandperiods.period'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
