# Generated by Django 3.2.6 on 2021-11-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('base', '0005_auto_20211101_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_sex',
            field=models.ForeignKey(max_length=254, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author'),
        ),
    ]
